### PR TITLE
Feature/sort

### PR DESCRIPTION
**Pull request by omrishtam**
can be seen in <http://omri.northeurope.cloudapp.azure.com/files>

### CODE REVIEW

**Comment by Shahar-Y** [comment]
Should the sort not happen in api-gateway?

**Comment by omrishtam** [comment]
> Should the sort not happen in api-gateway?

Currently it's done in the UI so we can give this function to users this week.

**Comment by Shahar-Y** [comment]
> > Should the sort not happen in api-gateway?
> > And what about sorting by date, size, etc...
> 
> Currently it's done in the UI so we can give this function to users this week.
> There's a sort by date, size, name.....


> > Should the sort not happen in api-gateway?
> 
> Currently it's done in the UI so we can give this function to users this week.

Got it. Looks great :+1:

**Review by Shahar-Y — APPROVED** [review]
LGTM

**Review by omerzamir — APPROVED** [review]

**Pull request merged**
